version: '3.8'
services:
  bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"  # настройте порт, если нужно
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

